application: qalogger
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: main/index.html
  upload: main/index.html

- url: /
  static_dir: main/

libraries:
- name: webapp2
  version: "2.5.2"

